version: '3.9'

services:
  app:
    image: node:16
    container_name: node_app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepassword
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: "npm start -r dotenv/config app.js"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
