version: '3.9'

services:
  app:
    build:
      context: .  # The context is the root directory where the Dockerfile for the app is located
      dockerfile: Dockerfile  # Optional if your Dockerfile is named 'Dockerfile'
    container_name: node_app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
